import React, { useMemo, useState } from 'react'
import './index.css'

type Provider = 'gemini' | 'openai' | 'claude' | 'deepseek'
type FileMap = Record<string, string>
type ChatMessage = { role: 'user' | 'assistant'; content: string }

const models: Record<Provider, string[]> = {
  gemini: ['gemini-2.5-flash', 'gemini-2.5-pro'],
  openai: ['gpt-4.1-mini', 'gpt-4.1'],
  claude: ['claude-sonnet-4-20250514', 'claude-3-5-haiku-latest'],
  deepseek: ['deepseek-chat', 'deepseek-reasoner'],
}

const initialTemplate: FileMap = {
  'generated-app/settings.gradle.kts': `pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }\ndependencyResolutionManagement { repositoriesMode.set(org.gradle.api.initialization.resolve.RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }\nrootProject.name="AI Generated App"\ninclude(":app")\n`,
  'generated-app/build.gradle.kts': `plugins { id("com.android.application") version "8.5.2" apply false; id("org.jetbrains.kotlin.android") version "1.9.24" apply false }\n`,
  'generated-app/gradle.properties': `org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8\nandroid.useAndroidX=true\nkotlin.code.style=official\n`,
  'generated-app/app/build.gradle.kts': `plugins { id("com.android.application"); id("org.jetbrains.kotlin.android") }\nandroid { namespace="com.example.aibuilder"; compileSdk=35; defaultConfig { applicationId="com.example.aibuilder"; minSdk=26; targetSdk=35; versionCode=1; versionName="1.0" }; compileOptions { sourceCompatibility=JavaVersion.VERSION_17; targetCompatibility=JavaVersion.VERSION_17 }; kotlinOptions { jvmTarget="17" }; buildFeatures { compose=true }; composeOptions { kotlinCompilerExtensionVersion="1.5.14" } }\ndependencies { val bom=platform("androidx.compose:compose-bom:2024.06.00"); implementation(bom); implementation("androidx.activity:activity-compose:1.9.1"); implementation("androidx.compose.material3:material3"); implementation("androidx.compose.ui:ui-tooling-preview"); debugImplementation("androidx.compose.ui:ui-tooling") }\n`,
  'generated-app/app/src/main/AndroidManifest.xml': `<manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:theme="@style/AppTheme" android:label="AI App"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity></application></application></manifest>\n`.replace('</application></application>', '</application>'),
  'generated-app/app/src/main/res/values/styles.xml': `<resources><style name="AppTheme" parent="android:style/Theme.Material.Light.NoActionBar"/></resources>\n`,
  'generated-app/app/src/main/java/com/example/aibuilder/MainActivity.kt': `package com.example.aibuilder\n\nimport android.os.Bundle\nimport androidx.activity.ComponentActivity\nimport androidx.activity.compose.setContent\nimport androidx.compose.material3.Text\nimport androidx.compose.runtime.Composable\n\nclass MainActivity : ComponentActivity() {\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContent { App() }\n    }\n}\n\n@Composable\nfun App() { Text("Generated by AI Android App Builder") }\n`,
}

function b64(value: string) {
  const bytes = new TextEncoder().encode(value)
  let binary = ''
  bytes.forEach((byte) => { binary += String.fromCharCode(byte) })
  return btoa(binary)
}

function cleanJson(text: string) {
  const match = text.match(/```(?:json)?\s*([\s\S]*?)```/i)
  return (match ? match[1] : text).trim()
}

async function callAI(provider: Provider, key: string, model: string, messages: ChatMessage[], image?: string) {
  if (provider === 'gemini') {
    const parts: any[] = []
    messages.forEach((message) => parts.push({ text: `${message.role.toUpperCase()}: ${message.content}` }))
    if (image) parts.push({ inline_data: { mime_type: 'image/png', data: image.split(',')[1] } })
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ contents: [{ role: 'user', parts }], generationConfig: { temperature: 0.2 } }),
    })
    const json = await response.json()
    if (!response.ok) throw new Error(json.error?.message || 'Gemini request failed')
    return json.candidates?.[0]?.content?.parts?.map((part: any) => part.text || '').join('') || ''
  }

  if (provider === 'claude') {
    const claudeMessages: any[] = messages.map((message) => ({ role: message.role, content: message.content }))
    if (image && claudeMessages.length) {
      const last = claudeMessages[claudeMessages.length - 1]
      claudeMessages[claudeMessages.length - 1] = {
        ...last,
        content: [
          { type: 'text', text: last.content },
          { type: 'image', source: { type: 'base64', media_type: 'image/png', data: image.split(',')[1] } },
        ],
      }
    }
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': key,
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true',
      },
      body: JSON.stringify({ model, max_tokens: 12000, messages: claudeMessages }),
    })
    const json = await response.json()
    if (!response.ok) throw new Error(json.error?.message || 'Claude request failed')
    return json.content?.map((part: any) => part.text || '').join('') || ''
  }

  const url = provider === 'openai' ? 'https://api.openai.com/v1/chat/completions' : 'https://api.deepseek.com/chat/completions'
  const openMessages: any[] = messages.map((message) => ({ role: message.role, content: message.content }))
  if (image && provider === 'openai' && openMessages.length) {
    const last = openMessages[openMessages.length - 1]
    openMessages[openMessages.length - 1] = { ...last, content: [{ type: 'text', text: last.content }, { type: 'image_url', image_url: { url: image } }] }
  }
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` },
    body: JSON.stringify({ model, messages: openMessages, temperature: 0.2 }),
  })
  const json = await response.json()
  if (!response.ok) throw new Error(json.error?.message || `${provider} request failed`)
  return json.choices?.[0]?.message?.content || ''
}

async function github(path: string, token: string, init: RequestInit = {}) {
  const response = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'X-GitHub-Api-Version': '2022-11-28',
      ...(init.headers || {}),
    },
  })
  const text = await response.text()
  let json: any
  try { json = JSON.parse(text) } catch { json = text }
  if (!response.ok) throw new Error(json.message || `GitHub HTTP ${response.status}`)
  return json
}

function App() {
  const [provider, setProvider] = useState<Provider>('gemini')
  const [model, setModel] = useState(models.gemini[0])
  const [aiKey, setAiKey] = useState('')
  const [ghToken, setGhToken] = useState('')
  const [owner, setOwner] = useState('')
  const [repo, setRepo] = useState('')
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [input, setInput] = useState('')
  const [busy, setBusy] = useState(false)
  const [status, setStatus] = useState('Ready — choose an AI, connect GitHub, then describe your app.')
  const [files, setFiles] = useState<FileMap>(initialTemplate)
  const [image, setImage] = useState('')
  const [connected, setConnected] = useState(false)
  const [lastRun, setLastRun] = useState<any>(null)

  const canSend = useMemo(() => Boolean(aiKey.trim() && input.trim() && !busy), [aiKey, input, busy])
  const canGitHub = useMemo(() => Boolean(ghToken.trim() && owner.trim() && repo.trim()), [ghToken, owner, repo])

  const saveSettings = () => {
    setStatus('Ready — settings are active for this browser session. Keys are never written into project files.')
  }

  const connectGitHub = async () => {
    if (!canGitHub) { setStatus('Enter GitHub token, owner and repository first.'); return }
    setBusy(true)
    try {
      const info = await github(`/repos/${owner.trim()}/${repo.trim()}`, ghToken.trim())
      setConnected(true)
      setStatus(`Connected to ${info.full_name} on branch ${info.default_branch}.`)
    } catch (error: any) {
      setConnected(false)
      setStatus(`GitHub connection failed: ${error.message}`)
    } finally { setBusy(false) }
  }

  const send = async () => {
    if (!canSend) return
    setBusy(true)
    const userMessage: ChatMessage = { role: 'user', content: input.trim() }
    const nextMessages = [...messages, userMessage]
    setMessages(nextMessages)
    setInput('')
    setStatus(`Connecting to ${provider === 'openai' ? 'ChatGPT / OpenAI' : provider}…`)
    try {
      const prompt = `You are the coding agent inside a GitHub-native, backendless Android app builder.\n\nUSER REQUEST:\n${userMessage.content}\n\nCURRENT PROJECT FILES:\n${JSON.stringify(files)}\n\nReturn ONLY valid JSON: {"message":"short user-facing explanation","files":{"path":"complete file content"},"delete":["path"]}. The files object must contain complete contents for every changed/new file. Keep Gradle compatible with AGP 8.5.2, Kotlin 1.9.24, Java 17 and compileSdk 35. The project must be a real Android app and must build with ./gradlew assembleDebug. Do not return markdown fences. Preserve useful existing code and make focused changes.`
      const answer = await callAI(provider, aiKey.trim(), model, [...nextMessages, { role: 'user', content: prompt }], image || undefined)
      const parsed = JSON.parse(cleanJson(answer))
      const updated = { ...files, ...(parsed.files || {}) }
      ;(parsed.delete || []).forEach((path: string) => delete updated[path])
      setFiles(updated)
      setMessages([...nextMessages, { role: 'assistant', content: parsed.message || 'Project updated successfully.' }])
      setStatus('App code updated. When ready, connect GitHub and push the project to start the APK build.')
      setImage('')
    } catch (error: any) {
      setMessages([...nextMessages, { role: 'assistant', content: `Build agent error: ${error.message}` }])
      setStatus('AI request failed. Check the selected provider, model and API key.')
    } finally { setBusy(false) }
  }

  const pushToGitHub = async () => {
    if (!canGitHub) { setStatus('Connect GitHub first by entering owner, repository and a fine-grained token.'); return }
    setBusy(true)
    try {
      setStatus('Creating one atomic Git commit…')
      const info = await github(`/repos/${owner.trim()}/${repo.trim()}`, ghToken.trim())
      const branch = info.default_branch || 'main'
      const ref = await github(`/repos/${owner.trim()}/${repo.trim()}/git/ref/heads/${encodeURIComponent(branch)}`, ghToken.trim())
      const baseCommit = await github(`/repos/${owner.trim()}/${repo.trim()}/git/commits/${ref.object.sha}`, ghToken.trim())
      const treeItems: any[] = []
      for (const [path, content] of Object.entries(files)) {
        const blob = await github(`/repos/${owner.trim()}/${repo.trim()}/git/blobs`, ghToken.trim(), {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ content: b64(String(content)), encoding: 'base64' }),
        })
        treeItems.push({ path, mode: '100644', type: 'blob', sha: blob.sha })
      }
      const tree = await github(`/repos/${owner.trim()}/${repo.trim()}/git/trees`, ghToken.trim(), {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ base_tree: baseCommit.tree.sha, tree: treeItems }),
      })
      const commit = await github(`/repos/${owner.trim()}/${repo.trim()}/git/commits`, ghToken.trim(), {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: 'AI Builder: generate/update Android app', tree: tree.sha, parents: [baseCommit.sha] }),
      })
      await github(`/repos/${owner.trim()}/${repo.trim()}/git/refs/heads/${encodeURIComponent(branch)}`, ghToken.trim(), {
        method: 'PATCH', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sha: commit.sha, force: false }),
      })
      setConnected(true)
      setStatus('Pushed successfully. GitHub Actions should start the Android APK build automatically.')
      await refreshBuildStatus()
    } catch (error: any) {
      setStatus(`GitHub push failed: ${error.message}`)
    } finally { setBusy(false) }
  }

  const refreshBuildStatus = async () => {
    if (!canGitHub) return
    try {
      const data = await github(`/repos/${owner.trim()}/${repo.trim()}/actions/workflows/build-android.yml/runs?per_page=1`, ghToken.trim())
      const run = data.workflow_runs?.[0]
      setLastRun(run || null)
      if (run) setStatus(`APK workflow: ${run.status}${run.conclusion ? ` / ${run.conclusion}` : ''}.`)
    } catch (error: any) { setStatus(`Could not read Actions status: ${error.message}`) }
  }

  const onImage = (file: File) => {
    const reader = new FileReader()
    reader.onload = () => setImage(String(reader.result))
    reader.readAsDataURL(file)
  }

  return (
    <div className="app">
      <header>
        <div><b>AI Android App Builder</b><span>Frontend-only • Your AI key • Your GitHub</span></div>
        <div className="header-actions"><span className={connected ? 'connected' : ''}>● {connected ? 'GitHub connected' : 'Not connected'}</span><button onClick={saveSettings}>Save</button></div>
      </header>
      <main>
        <aside>
          <div className="panel-title"><span>1</span><div><h3>AI connection</h3><small>Choose any supported provider.</small></div></div>
          <label>AI Provider
            <select value={provider} onChange={(event) => { const next = event.target.value as Provider; setProvider(next); setModel(models[next][0]) }}>
              <option value="gemini">Google Gemini</option><option value="openai">ChatGPT / OpenAI</option><option value="claude">Anthropic Claude</option><option value="deepseek">DeepSeek</option>
            </select>
          </label>
          <label>Model
            <select value={model} onChange={(event) => setModel(event.target.value)}>{models[provider].map((name) => <option key={name}>{name}</option>)}</select>
          </label>
          <label>API Key
            <input type="password" value={aiKey} onChange={(event) => setAiKey(event.target.value)} placeholder={`Paste your ${provider === 'openai' ? 'OpenAI' : provider} key`} autoComplete="off" />
          </label>
          <div className="hint">Your key is used directly by this browser. It is never sent to this project server and never committed to GitHub.</div>

          <div className="panel-title section-gap"><span>2</span><div><h3>GitHub connection</h3><small>Use a fine-grained token for your repository.</small></div></div>
          <label>Owner / Username<input value={owner} onChange={(event) => setOwner(event.target.value)} placeholder="your-username" /></label>
          <label>Repository<input value={repo} onChange={(event) => setRepo(event.target.value)} placeholder="my-android-app" /></label>
          <label>Fine-grained token<input type="password" value={ghToken} onChange={(event) => setGhToken(event.target.value)} placeholder="github_pat_..." autoComplete="off" /></label>
          <div className="row"><button className="secondary" onClick={connectGitHub} disabled={busy || !canGitHub}>Connect GitHub</button><button className="secondary" onClick={refreshBuildStatus} disabled={busy || !canGitHub}>Refresh build</button></div>
          <button className="primary full" onClick={pushToGitHub} disabled={busy || !canGitHub || Object.keys(files).length === 0}>☁ Push & Build APK</button>
          <div className="hint">Push creates one atomic commit. The repository's <b>Build Android APK</b> workflow runs automatically when generated files change.</div>
        </aside>

        <section className="chat">
          <div className="top"><div><div className="eyebrow">BUILD WORKSPACE</div><h2>Chat with AI and build your Android app</h2><p>{status}</p></div><a href={canGitHub ? `https://github.com/${owner}/${repo}/actions` : 'https://github.com/actions'} target="_blank" rel="noreferrer">GitHub Actions ↗</a></div>
          <div className="messages">
            {messages.length === 0 && <div className="welcome"><div className="bot-icon">✦</div><h1>What should we build?</h1><p>Describe the app in plain language. The AI edits a real Android project, then GitHub Actions compiles the APK.</p><div className="suggestions"><button onClick={() => setInput('Build a modern shopping app with login, product search, categories, cart, checkout and profile screens.')}>🛍 Shopping app</button><button onClick={() => setInput('Build a fitness app with dashboard, workout plans, progress charts and a profile screen.')}>🏃 Fitness app</button><button onClick={() => setInput('Inspect the current project and make it production-ready, fixing likely Gradle and Kotlin build issues.')}>🛠 Fix current project</button></div></div>}
            {messages.map((message, index) => <div key={`${message.role}-${index}`} className={message.role}><div className="role">{message.role === 'user' ? 'You' : 'AI Builder'}</div>{message.content}</div>)}
            {busy && <div className="assistant typing"><div className="role">AI Builder</div>Working…</div>}
          </div>
          {lastRun && <div className={`build-card ${lastRun.conclusion === 'success' ? 'success' : ''}`}><div><b>APK build</b><span>{lastRun.status}{lastRun.conclusion ? ` • ${lastRun.conclusion}` : ''}</span></div><a href={lastRun.html_url} target="_blank" rel="noreferrer">Open workflow ↗</a></div>}
          {image && <div className="attachment"><img src={image} alt="Attached reference" /><button onClick={() => setImage('')}>Remove</button></div>}
          <div className="composer"><label className="attach" title="Attach a screenshot">📎<input type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) onImage(file) }} /></label><textarea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); send() } }} placeholder="Tell the AI what to build or change…" /><button className="send" onClick={send} disabled={!canSend}>{busy ? '…' : 'Send ➤'}</button></div>
        </section>
      </main>
    </div>
  )
}

export default App
