import React, { useMemo, useState } from 'react'
import './index.css'

type Provider = 'gemini'|'openai'|'claude'|'deepseek'
const models: Record<Provider,string[]> = {
  gemini:['gemini-2.5-flash','gemini-2.5-pro'],
  openai:['gpt-4.1-mini','gpt-4.1'],
  claude:['claude-sonnet-4-20250514','claude-3-5-haiku-latest'],
  deepseek:['deepseek-chat','deepseek-reasoner']
}

type FileMap = Record<string,string>
const initialTemplate: FileMap = {
  'generated-app/settings.gradle.kts': `pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }\ndependencyResolutionManagement { repositoriesMode.set(org.gradle.api.initialization.resolve.RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }\nrootProject.name="AI Generated App"\ninclude(":app")\n`,
  'generated-app/build.gradle.kts': `plugins { id("com.android.application") version "8.5.2" apply false; id("org.jetbrains.kotlin.android") version "1.9.24" apply false }\n`,
  'generated-app/gradle.properties': `org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8\nandroid.useAndroidX=true\nkotlin.code.style=official\n`,
  'generated-app/app/build.gradle.kts': `plugins { id("com.android.application"); id("org.jetbrains.kotlin.android") }\nandroid { namespace="com.example.aibuilder"; compileSdk=35; defaultConfig { applicationId="com.example.aibuilder"; minSdk=26; targetSdk=35; versionCode=1; versionName="1.0" } compileOptions { sourceCompatibility=JavaVersion.VERSION_17; targetCompatibility=JavaVersion.VERSION_17 }; kotlinOptions { jvmTarget="17" }; buildFeatures { compose=true }; composeOptions { kotlinCompilerExtensionVersion="1.5.14" } }\ndependencies { val bom=platform("androidx.compose:compose-bom:2024.06.00"); implementation(bom); implementation("androidx.activity:activity-compose:1.9.1"); implementation("androidx.compose.material3:material3"); implementation("androidx.compose.ui:ui-tooling-preview"); debugImplementation("androidx.compose.ui:ui-tooling") }\n`,
  'generated-app/app/src/main/AndroidManifest.xml': `<manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:theme="@style/AppTheme" android:label="AI App"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity></application></manifest>\n`,
  'generated-app/app/src/main/res/values/styles.xml': `<resources><style name="AppTheme" parent="android:style/Theme.Material.Light.NoActionBar"/></resources>\n`,
  'generated-app/app/src/main/java/com/example/aibuilder/MainActivity.kt': `package com.example.aibuilder\n\nimport android.os.Bundle\nimport androidx.activity.ComponentActivity\nimport androidx.activity.compose.setContent\nimport androidx.compose.material3.Text\nimport androidx.compose.runtime.Composable\n\nclass MainActivity: ComponentActivity(){ override fun onCreate(savedInstanceState: Bundle?){ super.onCreate(savedInstanceState); setContent { App() } } }\n@Composable fun App(){ Text("Generated by AI Android App Builder") }\n`
}

function b64(s:string){ const bytes=new TextEncoder().encode(s); let bin=''; bytes.forEach(x=>bin+=String.fromCharCode(x)); return btoa(bin) }
function cleanJson(text:string){ const m=text.match(/```(?:json)?\\s*([\\s\\S]*?)```/i); return (m?m[1]:text).trim() }

async function callAI(provider:Provider,key:string,model:string,messages:any[],image?:string){
  if(provider==='gemini'){
    const parts:any[]=[]; for(const m of messages){ parts.push({text:`${m.role.toUpperCase()}: ${m.content}`}) }; if(image) parts.push({inline_data:{mime_type:'image/png',data:image.split(',')[1]}})
    const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts}],generationConfig:{temperature:.2}})}); const j=await r.json(); if(!r.ok) throw new Error(j.error?.message||'Gemini request failed'); return j.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').join('')||''
  }
  const url=provider==='openai'?'https://api.openai.com/v1/chat/completions':provider==='deepseek'?'https://api.deepseek.com/chat/completions':'https://api.anthropic.com/v1/messages'
  if(provider==='claude'){
    const claudeMessages=messages.map((m:any)=>({role:m.role==='assistant'?'assistant':'user',content:m.content}))
    if(image){ claudeMessages[claudeMessages.length-1].content=[{type:'text',text:claudeMessages[claudeMessages.length-1].content},{type:'image',source:{type:'base64',media_type:'image/png',data:image.split(',')[1]}}] }
    const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body:JSON.stringify({model,max_tokens:12000,messages:claudeMessages})}); const j=await r.json(); if(!r.ok) throw new Error(j.error?.message||'Claude request failed'); return j.content?.map((x:any)=>x.text||'').join('')||''
  }
  const openMessages:any[]=messages.map((m:any)=>({role:m.role,content:m.content}))
  if(image && provider==='openai'){ openMessages[openMessages.length-1].content=[{type:'text',text:openMessages[openMessages.length-1].content},{type:'image_url',image_url:{url:image}}] }
  const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model,messages:openMessages,temperature:.2})}); const j=await r.json(); if(!r.ok) throw new Error(j.error?.message||'AI request failed'); return j.choices?.[0]?.message?.content||''
}

async function gh(path:string, token:string, init:RequestInit={}){ const r=await fetch(`https://api.github.com${path}`,{...init,headers:{Accept:'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(init.headers||{})}}); const text=await r.text(); let j:any; try{j=JSON.parse(text)}catch{j=text}; if(!r.ok) throw new Error(j.message||`GitHub HTTP ${r.status}`); return j }

function App(){
 const [provider,setProvider]=useState<Provider>('gemini'); const [model,setModel]=useState(models.gemini[0]); const [aiKey,setAiKey]=useState(localStorage.getItem('ai_key')||''); const [ghToken,setGhToken]=useState(localStorage.getItem('gh_token')||''); const [owner,setOwner]=useState(localStorage.getItem('gh_owner')||''); const [repo,setRepo]=useState(localStorage.getItem('gh_repo')||''); const [messages,setMessages]=useState<any[]>([]); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [status,setStatus]=useState('Ready'); const [files,setFiles]=useState<FileMap>(initialTemplate); const [image,setImage]=useState<string>('');
 const canRun=useMemo(()=>!!aiKey&&!!input&&!busy,[aiKey,input,busy]);
 const save=()=>{localStorage.setItem('ai_key',aiKey);localStorage.setItem('gh_token',ghToken);localStorage.setItem('gh_owner',owner);localStorage.setItem('gh_repo',repo);setStatus('Settings saved locally');}
 const send=async()=>{ if(!canRun)return; setBusy(true); setStatus('AI is planning…'); const user={role:'user',content:input}; const next=[...messages,user]; setMessages(next); setInput(''); try{
   const prompt=`You are the coding agent for an open-source Android app builder. The current project files are JSON below. User request: ${input}\n\nCURRENT FILES:\n${JSON.stringify(files)}\n\nReturn ONLY valid JSON with this shape: {"message":"short explanation","files":{"path":"complete file content"},"delete":["path"]}. Modify only what is necessary, but you may create a complete serious Android application. Keep Gradle compatible with AGP 8.5.2/Kotlin 1.9.24 and Java 17. Never return markdown fences. The files object contains complete contents for changed/new files.`
   const out=await callAI(provider,aiKey,model,[...next,{role:'user',content:prompt}],image||undefined); const parsed=JSON.parse(cleanJson(out)); const nf={...files,...(parsed.files||{})}; (parsed.delete||[]).forEach((p:string)=>delete nf[p]); setFiles(nf); setMessages([...next,{role:'assistant',content:parsed.message||'Project updated.'}]); setStatus('Project updated locally.'); setImage('');
 }catch(e:any){setMessages([...next,{role:'assistant',content:`Error: ${e.message}`}]);setStatus('Error')}finally{setBusy(false)} }
 const push=async()=>{
   if(!ghToken||!owner||!repo){setStatus('Enter GitHub token, owner and repository first');return}
   setBusy(true);
   try{
     setStatus('Preparing one atomic Git commit…');
     const repoInfo=await gh(`/repos/${owner}/${repo}`,ghToken);
     const branch=repoInfo.default_branch||'main';
     const ref=await gh(`/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(branch)}`,ghToken);
     const baseCommit=await gh(`/repos/${owner}/${repo}/git/commits/${ref.object.sha}`,ghToken);
     const blobs:any[]=[];
     for(const [path,content] of Object.entries(files)){
       const blob=await gh(`/repos/${owner}/${repo}/git/blobs`,ghToken,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content: b64(String(content)), encoding:'base64'})});
       blobs.push({path,mode:'100644',type:'blob',sha:blob.sha});
     }
     const tree=await gh(`/repos/${owner}/${repo}/git/trees`,ghToken,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base_tree:baseCommit.tree.sha,tree:blobs})});
     const commit=await gh(`/repos/${owner}/${repo}/git/commits`,ghToken,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'AI Builder: update generated Android project',tree:tree.sha,parents:[baseCommit.sha]})});
     await gh(`/repos/${owner}/${repo}/git/refs/heads/${encodeURIComponent(branch)}`,ghToken,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha:commit.sha,force:false})});
     setStatus('Project pushed atomically. GitHub Actions can now build the complete generated-app.');
   }catch(e:any){setStatus(e.message||'GitHub push failed')}finally{setBusy(false)}
 }
 const onImage=(f:File)=>{const r=new FileReader();r.onload=()=>setImage(String(r.result));r.readAsDataURL(f)}
 return <div className="app"><header><div><b>AI Android App Builder</b><span> GitHub-native • BYO AI key</span></div><button onClick={save}>Save</button></header><main><aside><h3>Settings</h3><label>AI Provider<select value={provider} onChange={e=>{const p=e.target.value as Provider;setProvider(p);setModel(models[p][0])}}><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="claude">Claude</option><option value="deepseek">DeepSeek</option></select></label><label>Model<select value={model} onChange={e=>setModel(e.target.value)}>{models[provider].map(x=><option key={x}>{x}</option>)}</select></label><label>AI API Key<input type="password" value={aiKey} onChange={e=>setAiKey(e.target.value)} placeholder="Paste your own key"/></label><hr/><h3>GitHub</h3><label>Owner<input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="your-username"/></label><label>Repository<input value={repo} onChange={e=>setRepo(e.target.value)} placeholder="your-fork"/></label><label>GitHub token<input type="password" value={ghToken} onChange={e=>setGhToken(e.target.value)} placeholder="fine-grained token"/></label><button className="primary" onClick={push} disabled={busy}>Push project to GitHub</button><small>Token needs repository Contents read/write access. Keys stay in this browser and are never committed.</small></aside><section className="chat"><div className="top"><div><h2>Build your Android app</h2><p>{status}</p></div><a href={`https://github.com/${owner}/${repo}/actions`} target="_blank">Open Actions ↗</a></div><div className="messages">{messages.length===0&&<div className="welcome"><h1>Describe any Android app.</h1><p>Ask for a serious multi-screen product, attach a screenshot, iterate, then push the generated project to your fork and build a real APK with GitHub Actions.</p></div>}{messages.map((m,i)=><div key={i} className={m.role}>{m.content}</div>)}</div>{image&&<img className="preview" src={image}/>}<div className="composer"><label className="attach">📎<input type="file" accept="image/*" onChange={e=>e.target.files&&onImage(e.target.files[0])}/></label><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Build a complete Android application…"/><button className="send" onClick={send} disabled={!canRun}>Send</button></div></section></main></div>
}

export default App
